
name: 'wendelboe_tester_iceberg'
version: '1.0.0'
flags:
  send_anonymous_usage_stats: False  # Stopper datasending til dbt Labs
profile: 'wendelboe_tester_iceberg'

model-paths: ["models"]

clean-targets:
  - "logs"
  - "target"
  - "dbt_packages"


models:
  wendelboe_tester_iceberg:
    # Config indicated by + and applies to all files under models/example/
    example:
      +materialized: view
